# Generated by Django 4.2.3 on 2024-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
    ]
